publisher/artifactory/publisher.go
The path key should be lowercase, as it was in Godel 1.4.0. If this key is missing, Artifactory tries to compute SHA256 sums for the entire repository and fails because most publish users do not have sufficient permissions.
=> Fix path key in Artifactory SHA256 post body

distgo/config/config_test.go, distgo/config/configdist.go, distgo/config/internal/legacy/legacy.go, distgo/config/internal/v0/configdist.go, distgo/dist/dist.go, distgo/dist/dist_test.go, distgo/paramdist.go, integration_test/integration_test.go
Adds support for specifying an input directory for distributions.
The content of the specified input directory is copied to the
distribution work directory before the dister is run. Allows
custom excludes to be specified as well.
=> Add input-dir parameter to Dister

distgo/config/configdocker.go, distgo/config/internal/v0/configdocker.go, distgo/docker/docker_build.go, distgo/docker/docker_build_test.go, distgo/paramdocker.go
Adds configuration that allows the template rendering step for
Dockerfiles to be skipped.
=> Add disable-template-rendering option to DockerBuilder

Gopkg.lock, distgo/docker/docker_build.go
Ensure that Dockerfiles that are replaced with templated
versions are restored even when program is killed.
=> Update Docker build to clean up templated files

publisher/artifactory/publisher.go, publisher/maven/flags.go, publisher/maven/pom.go, publisher/mavenlocal/integration_test/integration_test.go, publisher/mavenlocal/publisher.go
Move common flags, configuration and logic to a single package
and share the logic rather than duplicating it.
=> Refactor Maven publisher logic

distgo/artifacts/artifacts_test.go, distgo/docker/docker_build.go, distgo/docker/docker_build_test.go, distgo/paramdocker.go, distgo/template.go
Change behavior so that the function automatically appends a '/'
if the rendered text does not contain it and add a {{RepositoryLiteral}}
function that mirrors the old behavior of rendering the unmodified
input.
=> Update Docker {{Repository}} template function

publisher/publisher_asset.go
Fix the way that boolean flags are passed to the asset publisher
to ensure that they are parsed properly. Fixes issue where publisher
assets always run in dry-run mode.
=> Fix publisher_asset dry-run issue

distgo/config/config_test.go, distgo/script.go, dockerbuilder/defaultdockerbuilder/config/config.go, dockerbuilder/defaultdockerbuilder/config/internal/v0/config.go, dockerbuilder/defaultdockerbuilder/dockerbuilder.go, dockerbuilder/defaultdockerbuilder/integration_test/integration_test.go
Provides the ability to specify arguments based on the execution
of a script.
Fixes #119
=> Add build-args-script to defaultdockerbuilder

dister/osarchbin/dister.go, dister/osarchbin/integration_test/integration_test.go
Previously, the `os-arch-bin` dister would only add the single binary file to the distribution archive, making it impossible for scripts to modify the format of the distribution. Now the archives contain all files that exist inside the architecture directory in the working directory. This leads to the same archives in the standard case, but will also include any script modifications.
I'm mostly proposing this to build asset files for Sensu, which uses separate archives per architecture, but has a specific directory layout inside each archive (mostly that binaries must appear directly in a `bin` directory.) Feel free to close this if you don't want to support it or if you think it should be a custom dister plugin instead.
=> Allow scripts to modify os-arch-bin dists

changelog/@unreleased/pr-174.v2.yml, publisher/artifactory/publisher.go, publisher/bintray/publisher.go, publisher/maven/pom.go, publisher/maven/pom_test.go, publisher/mavenlocal/publisher.go
At present, a single product with multiple distributions attempts to publish multiple POM files to the same location in the upstream repository. This causes runtime failures when the publisher doesn't have permissions to overwrite the first POM file, and it's logically inconsistent that a product should have multiple POM files to begin with.
Long term, POM generation should be extracted from the publisher's responsibilities. Then the publisher won't need to know whether or not it needs to generate a POM file for a given product's distribution - it will only be responsible for publishing. However, a simpler short-term fix (which allows us to introduce multiple disters for a single product) is to enforce that a product is only producing a single packaging extension and use that in the POM …
=> Resolve pom publishing inconsistency

changelog/@unreleased/pr-179.v2.yml, dockerbuilder/dockerbuildertester/dockerbuildertester.go
==COMMIT_MSG==
Fix: add module information in dockerbuildertester
Ensures that tests run by this harness work properly with Go modules.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/179)
=> Fix: add module information in dockerbuildertester

changelog/@unreleased/pr-191.v2.yml, dister/distertester/distertester.go
There are no public test functions to verify that all disters will be able to run build+dist multiple times with success. We have found that the `bin` and `os-arch-bin` disters do not currently succeed when run multiple times, which will be fixed in #189. However, any other dister outside of the built in ones should also be able to verify this behavior. Also related to the following issue: https://github.com/palantir/distgo/issues/190
==COMMIT_MSG==
Add public test to verify dist overwrites
==COMMIT_MSG==
The added public test verifies that running dist twice will succeed without error for the provided dister config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/191)
=> add public test to verify dist overwrites

dister/distertester/distertester.go
Some internal disters require the publisher groupID in order to build the dist correctly. Our internal dister appears to be the only one that requires extra metadata outside of the `DistersConfig` to build the dist, which makes this feel like a safe change. 
==COMMIT_MSG==
Update configuration used internally by the repeated dist test to specify a publish groupID, as there are some disters that require this information for the dist operation.
==COMMIT_MSG==
There may be other disters, now or in the future, that will require additional metadata, in which case it might make more sense to be less opinionated and allow users to provide the full product config.
cc @nmiyake 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add groupID to repeated dist test

changelog/@unreleased/pr-194.v2.yml, dockerbuilder/dockerbuildertester/dockerbuildertester.go
The `RunAssetDockerBuilderTest` only accepted a single asset provider, which meant that it was not possible to test Docker assets with non-builtin dist assets.
==COMMIT_MSG==
Adds the RunMultipleAssetDockerBuilderTest function to allow testing a Docker builder asset in conjunction with other assets.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/194)
=> Add RunMultipleAssetDockerBuilderTest function

changelog/@unreleased/pr-192.v2.yml, distgo/config/config_test.go, distgo/parambuild.go
Disters have no way to know what main package created the build output
==COMMIT_MSG==
Add mainPkg to BuildOutputInfo
==COMMIT_MSG==
cc @nmiyake I'll need you to merge+release since I don't have permission here
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/192)
=> improvement: Add mainPkg to BuildOutputInfo

changelog/@unreleased/pr-200.v2.yml, publisher/github/config/internal/v0/config.go, publisher/github/integration_test/integration_test.go, publisher/github/publisher.go
Fixes #199
The tags and releases created by the GitHub publisher never have a "v" prefix (even if the project itself has that prefix for a tag/version)
==COMMIT_MSG==
Adds configuration and flag to github publisher that adds a 'v'
prefix to the version used for the tag/release created by the
publisher.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/200)
=> github publisher: provide ability to add 'v' prefix for releases

changelog/@unreleased/pr-203.v2.yml, publisher/github/publisher.go
If a GitHub release already existed for a tag, the github publisher would fail.
==COMMIT_MSG==
Updates github publisher so that if a release for the tag being published already exists, artifacts are uploaded to the existing release rather than failing.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/203)
=> github publisher: handle case where release already exists

changelog/@unreleased/pr-222.v2.yml, publisher/artifactory/integration_test/integration_test.go, publisher/artifactory/publisher.go, publisher/common.go
The Artifactory publisher properties were not URL encoded, so any key/values that contain invalid URL parameters would fail to publish.
==COMMIT_MSG==
URL encode the Artifactory publisher property fields
Fixes a bug where the Artifactory properties were inserted into the URL without any encoding which caused failures when publishing. The properties will now be encoded before appending to the Artifactory URL.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/222)
=> Fix: URL encode the Artifactory publisher property fields

dister/distertester/distertester.go, distgo/artifacts/artifacts_test.go, distgo/build/imports/imports_test.go, distgo/clean/clean_test.go, distgo/config/config_test.go, distgo/dist/dist_test.go, distgo/printproducts/printproducts_test.go, dockerbuilder/dockerbuildertester/dockerbuildertester.go, integration_test/integration_test.go, internal/files/files.go, projectversioner/projectversiontester/projectversionertester.go, publisher/publishertester/publishertester.go
A break (no more template rendering) and a behavior change (using `packages.Load` to get module paths instead of `$GOPATH`) in `nmiyake/pkg/gofiles` blocked upgrades to this repo.
More context is laid out in https://github.com/nmiyake/pkg/issues/24
All usages of `gofiles.Write` did not inspect the returned import paths, so instead of using that function, we can use an internal function to write out the raw Go files avoiding any package loading and only returning errors for writing the files.
==COMMIT_MSG==
Write Go files with an internal helper instead of gofiles.Write
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/237)
=> Write Go files with an internal helper instead of gofiles.Write

changelog/@unreleased/pr-249.v2.yml, publisher/artifactory/publisher.go, publisher/bintray/publisher.go, publisher/common.go, publisher/github/publisher.go, publisher/mavenlocal/publisher.go
The built-in publishers would always attempt to publish all artifacts for a given distribution.
Generally, this is the desired behavior. However, if there are disters that create multiple different kinds of dist outputs, then there may be scenarios in which an end user would want to publish certain outputs using a particular publisher and other outputs using another publisher, and this was not previously possible.
Another scenario where this is useful is when a publish only partially succeeds and the user wants to perform the operation again but only for the artifacts that were not published.
==COMMIT_MSG==
Adds flags to the built-in publishers that enables controlling the behavior
of the artifacts that will be published by the operation.
If "--filter-artifact-names" is specified, then …
=> Add "filter-artifact-names" and "exclude-artifact-names" to publishers

changelog/@unreleased/pr-253.v2.yml, publisher/artifactory/integration_test/integration_test.go, publisher/artifactory/publisher.go
The artifactory publish operation would create and upload a POM file even if no artifacts were uploaded (for example, because of filters applied to artifact names).
==COMMIT_MSG==
Updates Artifactory publisher to upload a POM file only if the publish operation publishes at least 1 artifact.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/253)
=> Artifactory publisher: only upload POM if at least 1 artifact is uploaded

changelog/@unreleased/pr-318.v2.yml, cmd/build.go, distgo/build/build.go, distgo/build/build_test.go
This flag has been deprecated since Go 1.16 and removed in Go 1.20, so remove it from distgo build as well.
Fixes #317
Running the "build" command with the "--install" flag fails when using Go 1.20
==COMMIT_MSG==
Removes the "--install" flag for the "build" command. The underlying flag (the "-i" flag for the "go build" command) has been deprecated since Go 1.16 and was removed in Go 1.20.
==COMMIT_MSG==
Any existing calls that use the "--install" flag will no longer work (typically `./godelw build --install`). However, I have found no such uses that exist, and believe that removing existing usages should not be difficult.
If there is an unforeseen case it is always possible to re-add the flag but to make it a noop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Remove the '--install' flag for the build command

changelog/@unreleased/pr-329.v2.yml, dockerbuilder/defaultdockerbuilder/dockerbuilder.go, dockerbuilder/defaultdockerbuilder/integration_test/integration_test.go
#307 introduced the ability to produce multi-platform images built with `buildx`, the docker buildkit subcommand. Buildkit added some syntax to Dockerfiles that are not backwards compatible with the old `build` process. As a result, trying to write a Dockerfile that is both multi-platform and will work with the old `build` command (without enabling buildkit) is practically impossible. In order to keep the "API" of producing a local docker image, we'd need to update the daemon output type to use the buildkit backend.
==COMMIT_MSG==
Use buildx subcommand for docker daemon output builds. This fixes the docker daemon output type for dockerfiles which take advantage of various buildkit features, such as [platform args](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in …
=> Use buildx for docker daemon builds

changelog/@unreleased/pr-453.v2.yml, distgo/artifacts/artifacts_test.go, distgo/build/build_test.go, distgo/config/config_test.go, distgo/config/configproduct.go, distgo/config/configpublish.go, distgo/config/internal/v0/configproduct.go, distgo/docker/docker_build.go, distgo/env.go, distgo/parambuild.go, distgo/paramdist.go, distgo/paramdocker.go, distgo/paramproduct.go, distgo/template.go, publisher/maven/pom.go, publisher/maven/pom_test.go
==COMMIT_MSG==
Add support for overriding product name in config
==COMMIT_MSG==
- This enables individual disters and publishers to respect this configuration override in follow-on PRs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/453)
=> Improvement: Add support for overriding product name in config

changelog/@unreleased/pr-480.v2.yml, cmd/dist.go, distgo/clean/clean_test.go, distgo/dist/dist.go, distgo/dist/dist_test.go, distgo/docker/docker_build.go, distgo/docker/docker_build_test.go, distgo/publish/publish.go, distgo/publish/publish_test.go
- Add the ability to pipe through a Parallel flag into the dist CMD. Previously it was hardcoded to true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/480)
=> improvement: Add the ability to pipe through a Parallel flag into the dist CMD. Previously it was hardcoded to true

changelog/@unreleased/pr-501.v2.yml, distgo/config/config_test.go, distgo/config/configdefaults.go, go.mod, go.sum, vendor/github.com/palantir/godel/v2/framework/builtintasks/packages/packages.go, vendor/github.com/palantir/godel/v2/framework/godellauncher/defaulttasks/defaulttasks.go, vendor/github.com/palantir/pkg/pkgpath/godelw, vendor/github.com/palantir/pkg/pkgpath/packages.go, vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go, vendor/golang.org/x/mod/modfile/print.go, vendor/golang.org/x/mod/modfile/read.go, vendor/golang.org/x/mod/modfile/rule.go, vendor/golang.org/x/mod/modfile/work.go, vendor/golang.org/x/mod/module/module.go, vendor/golang.org/x/mod/module/pseudo.go, vendor/modules.txt
==COMMIT_MSG==
Uses the pkgpath module instead of "go list" to determine the main packages in a project if the distgo configuration does not declare products.
Fixes "go list" errors that occurred in repositories with multiple main packages when using Go 1.22.0 and later.
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/501)
=> Update logic for determining main packages

changelog/@unreleased/pr-516.v2.yml, distgo/build/build.go, distgo/build/build_test.go, distgo/config/configbuild.go, distgo/config/internal/v0/configbuild.go, distgo/parambuild.go
Previously, build configuration provided an `Environments` map that could be used to specify environment variables to set when building products as part of configuration.
However, such environment variables were always set for all builds, so it was not possible to write configuration that would set different environment variables based on the OS or the OS/Architecture of the targets.
The ability to do so can be useful for setting variables such as `CC` or `CGO_ENABLED` to configure how binaries for particular output targets are built (previously, this would require defining separate products per output target).
==COMMIT_MSG==
Adds the `os-environment` and `os-archs-environment` fields to build configuration to make it possible to specify environment variables that should be set when …
=> Adds the ability to specify environment variables for builds on a per-OS or OS/Architecture level

changelog/@unreleased/pr-517.v2.yml, distgo/build/build.go, distgo/build/build_test.go
Ensures that order of environment variables is consistent
==COMMIT_MSG==
Iterate over environment keys in sorted order to ensure stable ordering.
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/517)
=> Iterate over environment keys in sorted order

changelog/@unreleased/pr-586.v2.yml, dockerbuilder/defaultdockerbuilder/dockerbuilder.go
Right now cross platform build result has to be taken from the OCI output.
==COMMIT_MSG==
For convenience, we should allow cross platform build for docker output type as well and for this we need to pass the `--platform` arg.
If multiple platforms are specified, only the native platform will be picked. If one platform is specified, this platform will be picked even for cross platform.
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/586)
=> Pass the --platform arg with docker output type
