palantir/distgo

- README.md
This reverts commit d72f7aac9e85ccaa0a3ef3289f918f41de83bcef.
> Revert "Remove line breaks in README (#48)"

- dister/disters.go
- dockerbuilder/dockerbuilders.go
Fix issue where dister and dockerbuilder assets of the same type
incorrectly shared configuration between different products.
> Fix asset creation logic

- distgo/product.go
Ensure that dist outputs are processed in the order in which
they are produced by disters
> Maintain ordering of dist artifact outputs

- distgo/config/configdocker.go
- distgo/config/configproduct.go
- distgo/config/internal/legacy/legacy.go
- distgo/config/internal/v0/configdocker.go
- distgo/docker/docker_build.go
- distgo/env.go
- distgo/paramdocker.go
- dockerbuilder/defaultdockerbuilder/integration_test/integration_test.go
Also update migration code to migrate legacy build-args-script
field into the script field.
> Add script field to Docker configuration

- distgo/docker/docker_build_test.go
- distgo/paramdocker.go
- distgo/template.go
Ensure that trailing '/' is not appended if repository is empty.
> Fix behavior of Docker {{Repository}} function

- distgo/artifacts/artifacts_test.go
- distgo/config/config_test.go
- distgo/config/configdocker.go
- distgo/config/internal/legacy/legacy.go
- distgo/config/internal/v0/configdocker.go
- distgo/docker/docker_build_test.go
- distgo/docker/docker_push_test.go
- distgo/paramdocker.go
- distgo/productparams.go
- dockerbuilder/defaultdockerbuilder/integration_test/integration_test.go
Docker tags are ordered according to the map ordering in YAML.
Ensure that this ordering is maintained in code and when YAML is
marshaled.
> Ensure that Docker tags are ordered in config

- distgo/config/internal/v0/configdocker.go
- distgo/docker/docker_build.go
- distgo/docker/docker_build_test.go
- distgo/paramdocker.go
Allows indexing image tags based on name.
> Add Tag template function for Dockerfile rendering

- distgo/build/build.go
- distgo/build/build_test.go
- distgo/config/configbuild.go
- distgo/config/internal/legacy/legacy.go
- distgo/config/internal/v0/configbuild.go
- distgo/parambuild.go
- integration_test/integration_test.go
> Add script field to build configuration

- dister/bin/dister.go
- dister/bin/integration_test/integration_test.go
> Fix panic in bin dister

- Gopkg.lock
- Gopkg.toml
- cmd/root.go
- vendor/github.com/palantir/godel/framework/builtintasks/checkpath/checkpath.go
- vendor/github.com/palantir/godel/framework/builtintasks/githubwiki/githubwiki.go
- vendor/github.com/palantir/godel/framework/builtintasks/installupdate/install.go
- vendor/github.com/palantir/godel/framework/builtintasks/installupdate/layout/layout.go
- vendor/github.com/palantir/godel/framework/builtintasks/installupdate/update.go
- vendor/github.com/palantir/godel/framework/builtintasks/packages.go
- vendor/github.com/palantir/godel/framework/builtintasks/pluginsconfig.go
- vendor/github.com/palantir/godel/framework/builtintasks/upgradeconfig.go
- vendor/github.com/palantir/godel/framework/builtintasks/verify.go
- vendor/github.com/palantir/godel/framework/builtintasks/version.go
- vendor/github.com/palantir/godel/framework/godel/config/artifactresolver.go
- vendor/github.com/palantir/godel/framework/godel/config/godel.go
- vendor/github.com/palantir/godel/framework/godel/config/readconfig.go
- vendor/github.com/palantir/godel/framework/godel/config/upgradeconfig.go
- vendor/github.com/palantir/godel/framework/godellauncher/defaulttasks/defaulttasks.go
- vendor/github.com/palantir/godel/framework/godellauncher/godelcli.go
- vendor/github.com/palantir/godel/framework/godellauncher/task.go
- vendor/github.com/palantir/godel/framework/internal/pathsinternal/paths.go
- vendor/github.com/palantir/godel/framework/pluginapi/cobracli.go
- vendor/github.com/palantir/godel/framework/pluginapi/plugininfo.go
- vendor/github.com/palantir/godel/framework/pluginapi/v2/pluginapi/cobracli.go
- vendor/github.com/palantir/godel/framework/plugins/configprovider.go
- vendor/github.com/palantir/godel/godelgetter/download.go
- vendor/github.com/palantir/godel/pkg/products/v2/products/products.go
Uses the ReadGodelConfigExcludesFromFile function to make the
plugin more robust to godel configuration changes.
> Update godel dependency to 2.14.0 and update to read excludes

- go.mod
- go.sum
- vendor/github.com/palantir/distgo/pkg/git/LICENSE
- vendor/modules.txt
> Remove replace directive in go.mod

- go.mod
- go.sum
> Remove indirect module reference

- .circleci/config.yml
- changelog/@unreleased/pr-180.v2.yml
==COMMIT_MSG==
Update Go version to 1.14.4.
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/180)
> Update Go version to 1.14.4

- .circleci/config.yml
- distgo/artifacts/artifacts_test.go
- godel/config/test-plugin.yml
- pkg/git/godel/config/godel.properties
- pkg/git/godelw
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/204)
> Update CircleCI configuration

- .circleci/config.yml
- godel/config/test-plugin.yml
==COMMIT_MSG==
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/207)
> Update integration test criteria

- godel/config/godel.properties
- godelw
- pkg/git/godel/config/godel.properties
- pkg/git/godelw
==COMMIT_MSG==
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/208)
> Update godel to version 2.35.0

- godel/config/dist-plugin.yml
==COMMIT_MSG==
==COMMIT_MSG==
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/212)
> Add arm64 publishing to dist-plugin.yml

- changelog/@unreleased/pr-268.v2.yml
- distgo/template.go
- go.mod
- go.sum
- publisher/maven/git.go
- publisher/maven/git_test.go
- publisher/maven/pom.go
- publisher/maven/pom_test.go
- vendor/github.com/whilp/git-urls/.travis.yml
- vendor/github.com/whilp/git-urls/LICENSE
- vendor/github.com/whilp/git-urls/Makefile
- vendor/github.com/whilp/git-urls/README.md
- vendor/github.com/whilp/git-urls/urls.go
- vendor/modules.txt
_See internal infra-projects#73_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/268)
> feature: Include git remote and web url in maven pom.xml

- changelog/@unreleased/pr-454.v2.yml
- distgo/paramproduct.go
- distgo/paramproduct_test.go
==COMMIT_MSG==
Handle legacy plugins that do not include product name
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/454)
> Improvement: Handle legacy plugins that do not include product name

- changelog/@unreleased/pr-455.v2.yml
- publisher/common.go
==COMMIT_MSG==
Add product name support to artifactory publisher
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/455)
> Improvement: Add product name support to artifactory publisher

- .circleci/config.yml
==COMMIT_MSG==
==COMMIT_MSG==
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/distgo/510)
> Update CircleCI configuration to add circle-all job
